
version: 2

sources:
  - name: retail_source
    schema: "{{ env_var('STARROCKS_DB', 'retail_development') }}"
    tables:
      - name: raw_orders
        description: Raw orders data loaded via Stream Load
      - name: raw_customers
        description: Raw customers data
      - name: raw_products
        description: Raw products data
