version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: fact_daily_sales
    columns:
      - name: order_date
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id
      - name: status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['PENDING', 'COMPLETED', 'SHIPPED', 'CANCELLED']

    # Composite key unique test
    tests:
      - unique:
          arguments:
            column_name: "concat(order_date, '-', product_id, '-', status)"
